### ISSUE TITLE
Output dimensionality mismatch on small lstm model

### ISSUE THREAD

**Issue by alexander-camuto** [sonos/tract#1078]
As detailed in https://github.com/zkonduit/ezkl/issues/233, calling `.into_typed()` on a small lstm model causes the following error: 

```bash
[E] [0s, ezkl] - failed: Translating node #70 "_fc1_MatMul" MatMulInference ToTypedTranslator
Error: Translating node #70 "_fc1_MatMul" MatMulInference ToTypedTranslator

Caused by:
    Output mismatch after rewiring expansion for output #0: expected 128,F32 got 1,128,F32
```

To reproduce the issue I've created a repo with the model and the code we use to generate input and output facts: 

https://github.com/alexander-camuto/lstm-issue-repro

To reproduce the issue simply run the following from the main repo directory: 

```bash
RUST_LOG=trace cargo run 

```

**Comment by alexander-camuto** [comment]
@kali whoops I'm an idiot. Its public now

**Comment by kali** [comment]
So I have a fix for the underlying issue. The problem was with the LSTMs, but with the dense layers at the ends.

I think you could use the following to cook your model instead of the pretty convoluted code you currently use:

```
    model.set_output_fact(0, InferenceFact::default()).unwrap();
    let model = model.into_typed().unwrap().into_decluttered().unwrap();
    let batch_size = model.symbol_table.sym("batch_size");
    let model = model.concretize_dims(&SymbolValues::default().with(&batch_size, 1)).unwrap();
```

Also I noticed a weird pattern in the network, the batch_size dimension seams to disappear in LSTM_3, which is not something I expected, so if your model still misbehaves we may have another issue there.

**Comment by alexander-camuto** [comment]
Hey @kali thank you for the response. Would these simplifications above also translate to the InputFacts -- or should those still be set as we currently do ?

**Comment by kali** [comment]
Oups, sorry, missed a line of context, this should be put right after the unmodified model_for_read line, and replace all the rest. The logic is 
* remove the output fact set by the model in onnx (replacing it with the default which is empty) because onnx exporter usually over-constraint the model
* let tract analyse works (as part of the into_typed() call) and figure out all the shapes
* declare batch_size as a symbol
* substitute the symbol by 1 in all the model.

**Comment by alexander-camuto** [comment]
thanks that is definitely a lot cleaner
