### ISSUE TITLE
what would be the process for adding tflite support?

### ISSUE THREAD

**Issue by skewballfox** [sonos/tract#1086]
I saw #437 I know tflite is not currently supported. I was wondering what would have to be done to add support. 

I've used `flatc` (compiled from master branch) and the tflite schema to generate a rust module that makes it possible to load a model(basically following [this guide](https://orth.uk/flatbuffers/) except for rust). 

I assuming from the [tf docs on ops compatibilty](https://www.tensorflow.org/lite/guide/ops_compatibility) that the most of the ops have likely already been implemented for tensorflow. so I'm guessing what is mainly needed is some code to map from the ops  in the tflite file to the existing implementations for the ops. 

if it's relevant, the actual list of ops in the model I'm trying to use(at least according to [this script](https://stackoverflow.com/a/70748032) are the following: 
- shape
- strided_slice
- transpose
- reshape
- concatenation
-  Fill
- Pack
- while
- fully_connected
- logistic

**Comment by kali** [comment]
Well, you're on the right track here. This has been in a corner of my mind for a while, but well, I can't do everything.

I think the first thing to check is, is tflite "typeable" like nnef is, or are we more in a tf/onnx kind of situation where shapes can not be deduced trivially from the model file ?

If you can load the model by parsing the model nodes from inputs to outputs, and if at each step you can determine at least the ranks (number of dims) and element type of tensors, then you can convert it straightaway to tract TypedModel. If it is not the case, then we need to go to an InferenceModel, and that makes everything more complicated

Assuming tflite is "typed", your best source of inspiration is the nnef crate. Half of it (the `deser` bits) is about parsing and loading the nnef format. It also contains a lot of `ser` stuff that you can ignore because you want to read from `tflite`, not dump as `tflite`.


You can look at the Framework trait, which allow to parse the in two stages (first to an intermediate protomodel, then to a model). You can pick the registry idea (building a hashmap of operator name to operator constructors when initializing the framework).

Most of these ops exist in tract-core already, or can be translated to tract-core ops. TF StridedSlice is insanely complicated, but the work has been done already. "While" is not there and could be a big one, but we have started working on Scan to bring up support for onnx `loop` so it may get easier when we're done.

Then there is the question of testing. Ideally we want some pre-built unit cases suite (small networks with a single op or a couple of op along with test input and outputs). ONNX have these, and it was a great help. If not, we can use the many networks available in tflite form. One option is to make some python script that will run a model over an arbitrary input, dump all intermediate values in .npz files, then we can use tract command line to compare step-by-step tract results with the .npz reference.

Overall, I would welcome the inclusion of a tflite loader into tract, but well, it's a significant amount of work.

**Comment by skewballfox** [comment]
> I think the first thing to check is, is tflite "typeable" like nnef is, or are we more in a tf/onnx kind of situation where shapes can not be deduced trivially from the model file ?

looking at the data for the model I'm testing (it's a wakeword), it *looks* like both the data type and info on the shape is embedded directly in the model (not sure how to interpret the column labeled input, I'm assuming it's dimensions). 

> Overall, I would welcome the inclusion of a tflite loader into tract, but well, it's a significant amount of work.

unless I'm misunderstanding what you are talking about, loading the model from a tflite file might be easier than you are expecting. `flatc` is generating 23k lines of rust code from the schema file. using that this is pretty much all that was required to load the model:

```rust
use std::{fs, path::PathBuf};
mod tflite_generated;
use crate::tflite_generated::tflite::Model;

fn main() {
    let mut model_file_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    model_file_path.push("test_data/hey_mycroft.tflite");
    //get the model from file under projectroot/test_data
    let model_file = &*fs::read(model_file_path).unwrap();

    
    unsafe {
        let table = flatbuffers::Table::new(&model_file, 28);
        let model = Model::init_from_table(table);
        println!("Model version: {}", model.version());
    };
}

```
the unsafe was required for loading the table from memory, the 28 was the offset that may or may not be specific to this model. 

note some of the code might need to be manually overwritten(mainly the stuff relating to vectors), but eh, we'll see.

**Comment by skewballfox** [comment]
if you want to check out the autogenerated code from flatc, it's [here](https://github.com/skewballfox/tract/blob/tflite/tflite/src/tflite_generated.rs). I'm still making sense of all that's included, and whether anything will need to be rewritten for use in tract.

still pretty new to this

**Comment by kali** [comment]
> unless I'm misunderstanding what you are talking about, loading the model from a tflite file might be easier than you are expecting. `flatc` is generating 23k lines of rust code from the schema file. using that this is pretty much all that was required to load the model:

Well this is about what I was expecting to be honest. I may have mislead you with the nnef example, as it also has to parse the input formats. So the tensorflow-lite situation looks like a mix of the nnef case, where you can (hopefully) output a TypedModel straight away, and of the onnx/tf case where the protobuf (or flatbuffer) generated code acts provides the ProtoModel.

So your next step is to make sense of the flat buffer Model. (I find the fbs easier to read than the generated rust, TBH.) So the root type is Model, containing buffers (that I assume will contains the trained parameters) and subgraphs, the first of one being the actual model. The subgraph contains tensors, which will in turn use the buffers. These tensors are both the constants and the intermediate variables of your graph. From this you can build an actual tract TypedModel: creating the input(s) with `add_source`, then iterate over the operators and wire them one by one.

This is where you'll need a map of wiring functions, keyed by Operator type id, (one for each supported op), that will wire equivalent tract-core ops into the model. Some tflite op will be mapped to one single tract-core op, but some will may more a couple of ops.

You'll need to keep around a mapping from the flatbuffer tensor ids to tract OutletId. Finally you can designate the outputs with set_output_outlets().

I have mixed feeling about the extent of what is supported by tflite: a couple of years ago, the operator set was still small, so a full mapping to tract could have been an option. But I'm afraid tflite has finally taken the same path as tf and grew out of control...
