### ISSUE TITLE
Performance issues infering model after upgrade tract 0.19.x -> 0.20.x

### ISSUE THREAD

**Issue by Flocksserver** [sonos/tract#1128]
I added to a base transformer model two new layers for intent classification and entity recognition, converted it (as good as I know) to onnx and infer my model with tract 0.19.x. So far so good. The inference time is 100-130ms (Mac M1). Fair enough. Now I updated tract to 0.20.x and have inference time 30-45s 🤯

I have to admit, that I left out the "into_optimized" step (with 0.19. as well as with 0.20.) by loading the model, because of an error I don't understand with my current knowledge. 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed analyse for node #728 "_intent_classifier_linear_Gemm" Gemm

Caused by:
    0: Infering facts
    1: Applying rule inputs[0].shape[0] == outputs[0].shape[0]
    2: Impossible to unify Sym(batch) with Sym(Gemmlogits_dim_0).', 
```

But 100ms with 0.19.x is good enough for me.

Do you have a tip on how to fix or understand the performance problem with 0.20.x.? What was the main change in 0.20 that could lead to this problem?

**Comment by kali** [comment]
Hey, this is definitely a bug. 

The cause of the performance change is related to the change around the "canonical" representation of the matrix multiplications. I switched from the classical "numpy-like" representation of matmul to a EinSum-like thing that can work on any weird combination of axes. The numpy-like was actually more or less running the optimised code, while now the einsum is runnning naive code until it's not explicitely optimised.

As for your root issue, I think it may have a pretty simple origin. It looks like the inference engine, while trying to figure out the shapes of the tensors in the network, fails because it has two symbols (batch and GemmLogits_dim_0) which are conflicting. Usually this happens when an ONNX network over-specifies its input and outputs with inconsistent placeholders. Because they're actually placeholders in ONNX, not symbols as tract would expects. tract is a bit picky about that, but the simple fix is to just ignore the output shape specification. `.with_output_fact(0, Default::default())` after loading the model and before `into_optimized()` should do the trick and help you get better performance.

**Comment by kali** [comment]
Lol, I misread your question first, and got lost on my writting, so I just edited my comment from "definitely a bug" to "probably not a bug" :)

**Comment by Flocksserver** [comment]
Thanks for the reply.
I will try ti fix my outputs/onnx exports. `.with_output_fact(0, Default::default())` did not help. I think the error is on my onnx export side. But with your explanation I "understand" what changed in 0.20.

**Comment by chriamue** [comment]
I have the performance drop for [tiny-yolov2 on onnx].(https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/tiny-yolov2).

```sh
# tract-onnx = { version = "0.20" }
time cargo test default --release
test yolo::tests::default ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.62s

real    0m0,492s
user    0m0,389s
sys     0m0,107s
```

```sh
# tract-onnx = { version = "0.20" }
time cargo test default --release
test yolo::tests::default ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 4 filtered out; finished in 0.62s

real    0m0,698s
user    0m0,551s
sys     0m0,150s
```

Looks like nearly 50% drop (user    0m0,389s -> user    0m0,551s), but didn't make multiple inference, maybe it's the model loading part which takes time.
