### ISSUE TITLE
Improve Range to handle dynamic boundaries better

### ISSUE THREAD

**Issue by ismailmaj** [sonos/tract#1137]
loading [clip-vit-base-patch32](https://huggingface.co/openai/clip-vit-base-patch32/tree/main) fails with the error:

```
panicked at 'called `Result::unwrap()` on an `Err` value: Failed analyse for node #405 "/vision_model/embeddings/patch_embedding/Conv" ConvHir

Caused by:
    0: Infering facts
    1: Applying rule inputs[0].shape[1] == 1*{inputs[1].shape[1]}
    2: Impossible to unify Sym(num_channels) with Val(3).', src/lib.rs:42:27
```

I'm suspecting this is similar to #832.

Command used to fetch the model:
`optimum-cli export onnx --model openai/clip-vit-base-patch32`

**Comment by kali** [comment]
I suspect it's a simpler matter. Try adding "--onnx-ignore-output-shapes" to tract command line, or use .with_output_shape(0, Default::default) in the API.

**Comment by ismailmaj** [comment]
`tract model.onnx --onnx-ignore-output-shapes` still fails :disappointed:

I couldn't find with_output_shape, my current code is the following:
```
let model = tract_onnx::onnx()
        .model_for_read(&mut std::io::Cursor::new(model_bytes)).unwrap()
        .into_optimized().unwrap()
        .into_runnable().unwrap();
```

**Comment by kali** [comment]
Sorry, it's with_output_fact(), not _shape, right after the unwrap(), before the into_optimized().
But if the comment line does not work, I will probablu have to look at the model. Can you prepare and share a model in .onnx to spare me the trouble ?

**Comment by ismailmaj** [comment]
Thank you for looking into this!
Here is the download link: [model.onnx](https://drive.google.com/file/d/1BWE6H2JOlGVRw5G7oCaMGHniYjGuEY-7/view?usp=sharing)

**Comment by kali** [comment]
OK, there are multiple issues with this model. Some of them are easy to fix in the model, some of them may need tract to be patched.

# Image model input constraints

First, the vision model input is specified with input of arbitrary size, but internal constraints impose fixed sized:
```
% tract --onnx-ignore-output-shapes  model-1137.onnx | grep -C1 -B0 Source
┏ 0 Source input_ids
┃   ━━━ text_batch_size,sequence_length,I64
--
┃┃┃┃┃┃┃┃┃┏ 2 Source attention_mask
┃┃┃┃┃┃┃┃┃┃   ━━━ text_batch_size,sequence_length,I64
--
┃┏ 1 Source pixel_values
┃┃   ━━━ image_batch_size,num_channels,height,width,F32
[2023-08-06T09:16:33.654976436Z ERROR tract] Error at stage analyse

    Caused by:
        0: Failed analyse for node #405 "/vision_model/embeddings/patch_embedding/Conv" ConvHir
        1: Failed analyse for node #405 "/vision_model/embeddings/patch_embedding/Conv" ConvHir
        2: Infering facts
        3: Applying rule inputs[0].shape[1] == 1*{inputs[1].shape[1]}
        4: Impossible to unify Sym(num_channels) with Val(3).
[1]    1581551 exit 1     cargo run -p tract -- --onnx-ignore-output-shapes model-1137.onnx |
       1581552 done       grep -C1 -B0 Source
```

After a bit of trial and error, i came with these constraints on the image input.

```
--onnx-ignore-output-shapes  model-1137.onnx -i text_batch_size,sequence_length,I64 -i 1,3,224,224,F32 -i text_batch_size,sequence_length,I64
```

# Sequence_length and range

But next we come to this one:

```
[2023-08-06T09:19:49.948192798Z ERROR tract] Error at stage type

    Caused by:
        0: Translating node #114 "/text_model/Range" Range ToTypedTranslator
        1: Range needs fixed inputs
```

Digging up a bit, the range operator is unhappy because it expects the range boundaries to be constant, while the max value is `sequence_length`.

So, depending on your use case, sequence_length may be know at model loading time, if you process one input. With this input specification, the model loads: ` -i 1,27,I64 -i 1,3,224,224,F32 -i 1,27,I64`. I picked 27 as a sequence len, and a batch size of 1.

If you want to process more than one input, it will be very un-efficient to load the model again and again for each input to adjust the sequence_length.

So I'll keep this issue open, we probably need tract Range op to become fully dynamic.
