### ISSUE TITLE
Error: Failed analyse for node #796 "Add_645" Add

### ISSUE THREAD

**Issue by GraesonB** [sonos/tract#1225]
Rest of the message:

```
Caused by:
    0: Infering facts
    1: Applying rule outputs[0].shape == batch,sequence,384
    2: Unifying shapes batch,sequence,Addlast_hidden_state_dim_2 and batch,sequence,384
    3: Impossible to unify Sym(Addlast_hidden_state_dim_2) with Val(384).
```

my code:

```rust
use std::{ path::{ PathBuf, Path }, str::FromStr };
use tract_onnx::{
    self,
    prelude::{ Framework, InferenceModelExt, Tensor, tvec },
    tract_hir::tract_ndarray,
};
use tokenizers::tokenizer::{ Result, Tokenizer };

fn main() -> Result<()> {
    let model_dir = PathBuf::from_str("./model")?;
    let tokenizer = Tokenizer::from_file(Path::join(&model_dir, "tokenizer.json"))?;

    let text = "test text";

    let tokenizer_output = tokenizer.encode(text, true)?;

    let input_ids = tokenizer_output.get_ids();
    let attention_mask = tokenizer_output.get_attention_mask();
    let token_type_ids = tokenizer_output.get_type_ids();
    let length = input_ids.len();

    println!("{:?}", input_ids);

    let model = tract_onnx
        ::onnx()
        .model_for_path(Path::join(&model_dir, "model.onnx"))?
        .into_optimized()?
        .into_runnable()?;

    Ok(())
}
```

I'm trying to load in all-MiniLM-L6-v2.onnx found [here](https://huggingface.co/optimum/all-MiniLM-L6-v2).

I'm very excited about this project, any help would be much appreciated.
I don't get the error when I take out .into_optimized() though. Is it not possible to optimize certain models?

**Comment by GraesonB** [comment]
Found a different version that works:
https://huggingface.co/Xenova/all-MiniLM-L6-v2

**Comment by kali** [comment]
ONNX model are not using symbols in the same way as tract. You are maybe the 100th person to run into this problem :)

Fix is relatively trivial: add `.with_output_fact(0, Default::default())?.with_output_fact(1, Default::default())?` after model_for_path(). This will erase the "bogus" (from tract point of view) shapes from the ONNX model.

Alternatively, try switching to the main branch of tract, I am now ignoring ONNX output shapes by default because this is too annoying. The change will appear on the 0.20.x whenever I cut a new release.

**Comment by GraesonB** [comment]
Ah I see, thanks for the help :-).
