### ISSUE TITLE
Support for Conv2DTranspose / ConvTranspose ONNX 10

### ISSUE THREAD

**Issue by discordance** [sonos/tract#198]
Hello !
Was trying tract and so far it looks amazing.

While playing with a conv autoencoder model, I noticed that the Deconvolution layers are not supported in ONNX and Tensforflow.

Would it be hard to implement it ? I looked at the code but so far my skills are very limited as I really don't understand well deconvolution.

I could try to implement it, because i feel that this op is not very different from the Conv layer.
The thing is that dynamic outputs might be problematic.

Very good job so far ! it's a pleasure to see something so advanced in pure rust.

Cheers

**Comment by kali** [comment]
Hi ! thanks for your interest in tract and the kind words.

It's true that ConvTranspose is not implemented. The few number of real-life models that were actually using it made it a low priority item.

I am not too sure how hard it would be to implement it. A simple, naive implementation would probably be easy for somebody with a good understanding of what Deconv is. Once we have this, a significant part of the work done for the convolution could probably be leveraged to optimise it later.

Note that going beyond the easy, naive implementation might be a daunting task. It took me more that a year of calendar time and several month of actual work to get the convolution operators in the state they are now, and I'm still not 100% happy about them. But depending on how heavily your model uses the Deconv operators, a relatively naive implementation may be enough for your use-case.

I am not too sure what makes you think dynamic outputs would get in the way. I can't see from the operator description where it would be required (with the usual assumption about hyper parameters and trainable inputs being constants at inference time). But dynamic size operators is not something I would be eager to add to tract infrastructure. I have shied away from the ops that make use of it so far.

**Comment by discordance** [comment]
Thx for your insights!

I can imagine how this could be daunting.
Yeah, by dynamic outputs I was talking about unknown output shapes like [-1, -1, -1, 64].

I am looking at https://github.com/onnx/onnx/blob/master/docs/Operators.md to get a better idea about the task and will read about deconv.

**Comment by kali** [comment]
OK, usually that kind of thing is not a problem, provided that tract analyse step can figure out the size from the operators constraints and the actual model input size. In practise this only fails if: 
1/ the input is not of constant size, 
2/ or if after simplification (eager evaluation and constant folding) there are still operators which output size depends on variable input data (like a convolution where an explicit variable padding parameter)

On top of that, we can venture into the semi-experimental terrain with the pulse capabilities. I mention this because I think autoencoder may fall into the right category here. This is a way to deal with a streaming input of arbitrary and unknown length (for application such as voiced keyword spotting). One dimension of the input tensor can take the magic value "S" (for stream). Provided that "it makes sense" and the pulse transformation is implemented for all the operators, tract can translate such a network into a stateful "pulsing" network: you would then push data into the network in "pulse", chunk of constant size and the network would output chunks of outputs. We already have implemented "pulsing" for regular convolution, recurring operators (LSTM and co) and have been using them in production for deep convolutional networks (wavenet, resnet) for nearly a year.

**Comment by kali** [comment]
Done and released.
