### ISSUE TITLE
Unable to load an object detector model using the tensorflow example

### ISSUE THREAD

**Issue by danielbank** [sonos/tract#429]
Preface: Hi, I'm kind of a ML noob so there is a good chance that this is just bone-headed mistakes on my end but I thought I would post on the off-chance that I can get some advice.  I can close this issue if it is unhelpful.

So I trained a model following along with an [object detection API tutorial](https://medium.com/tensorflow/training-and-serving-a-realtime-mobile-object-detector-in-30-minutes-with-cloud-tpus-b78971cf1193).  I was seeing if I could load the resulting model in the `example-tensorflow-mobilenet-v2` example.  The first thing I noticed is that I had to remove `.to_rgb8()` from this line:

```
  let image = image::open("grace_hopper.jpg").unwrap().to_rgb8();
```

It was causing an error:
```
no method named `to_rgb8` found for enum `image::DynamicImage` in the current scope
```

After doing that, I could compile but got the following runtime error:

```
     Running `/Users/DanielBank/workspace/tract/target/debug/example-tensorflow-mobilenet-v2`
Error: Translating node #854 "FeatureExtractor/MobilenetV1/fpn/top_down/nearest_neighbor_upsampling/resize_nearest_neighbor" Unimplemented(ResizeNearestNeighbor) ToTypedTranslator
```

**Comment by kali** [comment]
Hello @danielbank, thanks for your interest in tract !

Tensorflow is a huge beast, with dozens of operators that are only really used in one dark corner of the ecosystem. As we have limited resources, we focus the energy on supporting ONNX which is more manageable, and plugging in tensorflow when they make sense. Also, we do not support tensorflow2 format directly, and may never do so. For ONNX, tract has an estimated 85% operator support. So ususaly your best guess when getting started with tract is to pick an ONNX network instead of a tensorflow one. 

Here, your incarnation of mobilenet makes use of TF operator ResizeNearestNeighbor which is not implemented by tract. Sometimes it is just a matter of plugging in the TF op to the matching backend implementing the equivalent ONNX operators, but in this case, I have to say that ONNX Resize is not fully implemented yet so I can not offer you a quick fix.
