### ISSUE TITLE
Error: duplicate name

### ISSUE THREAD

**Issue by Rikorose** [sonos/tract#561]
Hi there,

i worked around some rank mismatch errors and am now at into_optimized() for my last module and getting this error. Here are some [logs](https://github.com/sonos/tract/files/7374367/clcop_export.log) and an [onnx file](https://github.com/sonos/tract/files/7374375/dfop_step.zip).
```
Error: duplicate name Slice_31
```

I am trying to export this operation:
https://github.com/Rikorose/DeepFilterNet/blob/feat_export/DeepFilterNet/df/dfop.py#L159
Which is essentially a filter operation that depends on past (and sometimes also future) time steps.

exported like this:
https://github.com/Rikorose/DeepFilterNet/blob/feat_export/DeepFilterNet/df/export.py#L206
The tract side:
https://github.com/Rikorose/DeepFilterNet/blob/feat_export/df-tract/src/main.rs#L159

**Comment by kali** [comment]
Hey, haven't look at your network, I will do if you can't find the issue on your own, but this one is usually relatively easy to fix, way eaiser than rank mismatch problems. :) It usually happens when, while patching a network (typically during declutter or codegen) two nodes are wired with the same name (or a node in the patch re-use the name from the rest of the network). The fix usually boils down to adding a suffix to a newly created node name in a wire_node call.

Sometimes, it may be helpful to add the `--feature paranoid_assertions` in tract_core. It will detect more errors earlier, but is prohibitively expensive, even to run the test suite on a daily basis.

Tell me if you can't find it easily.

**Comment by kali** [comment]
Sorry, I realize I was not clear earlier, this is most definitely a bug tract, your model is probably fine.
