### ISSUE TITLE
Protobuf decoding error

### ISSUE THREAD

**Issue by cauliflowew** [sonos/tract#651]
I'm trying to run basic inference on ONNX models using the `tract-onnx` crate, but every time I get the following protobuf error:

```Error: failed to decode Protobuf message: ModelProto.ir_version: invalid wire type: LengthDelimited (expected Varint)```

Trying to run unmodified code from examples folder also gives the same error. I'm using macOS v12.2.1 on arm64 architecture.

**Comment by kali** [comment]
Hello!

This message typically occurs when a protobuf file is broken... I just did a successful examples/onnx-mobilenet-v2 test on my own M1 (not the same OS version though) and I noticed that the links to model download where broken. I just fixed them. So if you're testing with one of those, could you check that the file do not contains some kind of 404 error message instead of a protobuf model... ?
