### ISSUE TITLE
Calling operators directly for AOT compilation instead of interpretation of ONNX model

### ISSUE THREAD

**Issue by VariantXYZ** [sonos/tract#937]
Related to #393 

I believe that a significant number of models will benefit from being compiled ahead of time instead of relying on the interpreter.

Specifically, doing so would allow:
* Reducing size of code by avoiding including unnecessary things that can't be stripped out due to being part of the interpreter (e.g. unused ops and serializers)
* Allowing rustc/llvm to validate and optimize further for specific targets (for a single model, if input sizes are known, this would allow for more compile-time validation)

I'm sure this will not be trivial for all models, but I think this could be a very beneficial low-hanging fruit for some models.

Assuming we have a model in the NNEF format, I'm wondering if the generated graph.nnef and dat files could be used to generate parametrized functions for direct calls. From the NNEF, this seems possible, but I'd like to verify and possibly get some more understanding of the .dat file format.

(The end-goal in my mind would be to have the tract CLI take a NNEF, optimize it, and spit out a rust file with a function call)

**Comment by kali** [comment]
This scenario makes sense. A couple of teams are actually doing similar things: use tract to load and declutter models, and once this is done fork away to an alternative runtime or a code generator, which is free to choose which subset it wants to optimize. The basic assumption being, tract-core MIR level graph description is canonical enough and stable enough for this. I am also open to discussion about including more operators in tract-core where there is significant opportunities for optimisation that are helped by keeping operators together instead of splitting them in atomic operations (typically, activation functions).

For practical reasons (limited resources, managing the project size, ...) I am happy to leave these developments happen outside of tract. While I do not make strong commitments on tract-core API stability, I am aware that teams are using it and try not to break it unnecessarily.

**Comment by VariantXYZ** [comment]
I was actually thinking about just doing direct calls to tract's internal operators, since it doesn't make much sense to me to not take advantage of it.

In my mind, flow would be to use tract cli to dump to NNEF/tract-core MIR and then that could be used to generate a file which implements a "run" function with fixed size inputs and outputs. Something like that could exist in a different project, to avoid affecting tract's scope.

The run function would be doing direct calls to the internal operator implementations to start. Things like MMMKernel selection would still happen, though ideally I'd like to be able to propagate that information down to so even that selection was static for a particular layer...

I'm not sure if such an approach is sane or not though, as I feel my understanding of tract's internals are middling at best. The other thing that concerns me is how exactly the nnef/dat files get parsed/used.

**Comment by kali** [comment]
The current flow for NNEF is:
1. load the model: parse the graph.nnef, load the .dat file as tensors in memory, represent it as a TypedModel
2. declutter the TypedModel from serialisation and training artefact (semantic, cross platforms optimisations)
3. "codegen": locale optimisation taking into account some platform dependent issues and particular case (convolution become depthwise or im2col+matmul at this stage, multiplier geometries are chosen, ...)
4. find out a working evaluation order and intermediary variable liveness rules (Runnable, aka SimplePlan)

At this stage we are ready to evaluate. We have in our hands an ordered list of operators to call, we just need to track input and output variables according to the rules. The operator invocation is dynamic, so this may hide some optimisation opportunities.

For ONNX, the first stage is more involved, but once we have a TypedModel we follow the same story from stage 2.

Only the output of 2 can be serialized to NNEF. Beyond that stage, the model is not "portable" anymore.

TBH, I am not sure we are missing that many optimisation opportunities, or that they are pushed beyond reach because of the way the interpreter loop works. I would need some examples to be convinced. But it is certain that we would get a smaller runtime if only the used code was embedded in the binary. Is it worth the trouble though ?

**Comment by VariantXYZ** [comment]
> Is it worth the trouble though ?

Finding out how much trouble there is was the purpose of this issue :)!

**Comment by kali** [comment]
Closing as not actionable.
